### ISSUE TITLE
如何在移动端禁止浏览器屏幕滚动

### ISSUE THREAD

**Issue by wuweijia** [wuweijia/BLOG#20]
# 如何在移动端禁止浏览器屏幕滚动
有时候我们希望弹出一个遮罩层后屏幕是不能滚动的。

> 这个问题在pc端一条css属性就可以fix,但是手机上却不能这样使用.
```css 
body {overflow: hidden}
```

> mobile 方案

禁止：
``` document.body.style.position = 'fixed';```

恢复：
``` document.body.style.position = 'static';```
